# Generated by Django 3.0.6 on 2020-05-13 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200512_0502'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-date_pub']},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ['title']},
        ),
    ]
