# Generated by Django 3.0.6 on 2020-05-14 14:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200513_2148'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='body',
            new_name='author',
        ),
        migrations.AddField(
            model_name='post',
            name='filename',
            field=models.CharField(db_index=True, default=datetime.date.today, max_length=150, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='similardoc_filename',
            field=models.CharField(db_index=True, default=datetime.date.today, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='similardoc_title',
            field=models.CharField(db_index=True, default=datetime.date.today, max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='section',
            name='slug',
            field=models.SlugField(blank=True, max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='title',
            field=models.CharField(max_length=150),
        ),
    ]
